name: autowalk 

on:
  schedule:
    - cron: 0 13 * * *
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
      - name: Init Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Walk 
        run: |
          pip install requests
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
        
          python3 main.py <<EOF
          ${user}
          ${pwd}
          EOF
